### ISSUE TITLE
Practica 1: Prototipo de interfaz

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/practicaprototipos-equipohjf#4]
Subir el Link de la interfaz hecha en Figma

**Comment by FedericoVictorianoSierra** [comment]
https://www.figma.com/proto/1rUppt9Z9JPOFD4a6fFhRw/Untitled?node-id=198%3A148&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=198%3A148

**Comment by Heidi-19** [comment]
Link del prototipo:
[https://www.figma.com/proto/1rUppt9Z9JPOFD4a6fFhRw/Untitled?node-id=198%3A148&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=198%3A148](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipohjf/issues/url)

**Comment by JoseABCruz** [comment]
Link del prototipo:
[https://www.figma.com/proto/1rUppt9Z9JPOFD4a6fFhRw/Untitled?node-id=198%3A148&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=198%3A148](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipohjf/issues/url)

**Comment by Practica-interfaz-visual-studio** [comment]
El porcentaje obtenido en esta practica es: 100%

**Comment by IrvingFernand0** [comment]
Calificación practica 1: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
