### ISSUE TITLE
Reporte de Practica 1

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/practicaprototipos-equipohjf#5]
Subir El Reporte de la Practica 1

**Comment by JoseABCruz** [comment]
[Practica 1 Prototipo de Interfaz gráfica.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipohjf/files/8058209/Practica.1.Prototipo.de.Interfaz.grafica.pdf)

**Comment by FedericoVictorianoSierra** [comment]
[Practica 1 Prototipo de Interfaz gráfica.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipohjf/files/8058228/Practica.1.Prototipo.de.Interfaz.grafica.pdf)

**Comment by Heidi-19** [comment]
[Practica 1 Prototipo de Interfaz gráfica.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipohjf/files/8058252/Practica.1.Prototipo.de.Interfaz.grafica.pdf)

**Comment by Heidi-19** [comment]
Link del prototipo:
[https://www.figma.com/proto/1rUppt9Z9JPOFD4a6fFhRw/Untitled?node-id=198%3A148&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=198%3A148](url)

**Comment by Practica-interfaz-visual-studio** [comment]
El porcentaje obtenido e esta practica es 100%

**Comment by IrvingFernand0** [comment]
Calificación practica 1: 20%

**Comment by josealfredo79** [comment]
Bien hecho...
